version: "3"
services:
  efiss-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: thaiduongme/efiss-backend:latest
    expose:
      - 3000
    depends_on:
      - redis
    volumes:
      - ./ecosystem.config.js:/efiss-backend/ecosystem.config.js
      - ./.env:/efiss-backend/.env
    networks:
      - efiss
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
  redis:
    image: "redis:latest"
    networks:
      - efiss
    expose:
      - "6379"

networks:
  efiss:
    driver: bridge
