version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: reverse-proxy-nginx
    restart: on-failure
    network_mode: "host"
    depends_on:
      - efiss-backend
      - redis
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/snippets:/etc/nginx/snippets
    - ./nginx/certs:/etc/nginx/certs

  efiss-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: thaiduongme/efiss-backend:latest
    container_name: efiss-backend
    restart: on-failure
    network_mode: "host"
    expose:
      - 3000
    depends_on:
      - redis
    volumes:
      - ./ecosystem.config.js:/efiss-backend/ecosystem.config.js
      - ./.env:/efiss-backend/.env
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: "redis:latest"
    container_name: redis
    restart: on-failure
    # network_mode: "host"
    networks:
      - efiss
    expose:
      - "6379"
    ports:
     - "127.0.0.1:6379:6379"
  
  efiss-ai:
    image: asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/efiss-ai:latest
    container_name: efiss-ai
    restart: on-failure
    expose:
      - "5000"
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/ping || exit 1"]
      interval: 120s
      timeout: 30s
      retries: 5
    

networks:
  efiss:
    driver: bridge
