version: "3"
services:
  efiss-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: thaiduongme/efiss-backend:latest
    depends_on:
      - redis
    volumes:
      - ./ecosystem.config.js:/efiss-backend/ecosystem.config.js
      - ./.env:/efiss-backend/.env
    networks:
      - efiss
  redis:
    image: "redis:latest"
    networks:
      - efiss
    expose:
      - "6379"

networks:
  efiss:
    driver: bridge
