version: "3"
services:
  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: custom-nginx:latest
    container_name: reverse-proxy-nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    networks:
    - efiss
    extra_hosts:
      - "host.docker.internal:host-gateway"  # https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach
    depends_on:
      - efiss-backend
      - redis
    volumes:
    - ./nginx/nginx.conf:/usr/local/nginx/conf/nginx.conf
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/snippets:/etc/nginx/snippets
    - ./nginx/certs:/etc/nginx/certs

  efiss-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: thaiduongme/efiss-backend:latest
    container_name: efiss-backend
    restart: on-failure
    networks:
      - efiss
    extra_hosts:
      - "host.docker.internal:host-gateway"
    expose:
      - 3000
    depends_on:
      - redis
    volumes:
      - ./ecosystem.config.js:/efiss-backend/ecosystem.config.js
      - ./.env:/efiss-backend/.env
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  redis:
    image: "redis:latest"
    container_name: redis
    restart: on-failure
    networks:
      - efiss
    expose:
      - "6379"
  
  efiss-ai:
    image: asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/efiss-ai:latest
    container_name: efiss-ai
    restart: on-failure
    expose:
      - "5000"
    ports:
      - "5001:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:5000/ping || exit 1"]
      interval: 120s
      timeout: 30s
      retries: 5
    env_file:
      - .env
    

networks:
  efiss:
    driver: bridge
