name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Build docker images
      run: docker compose build
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Create secret .env file
      run: 'echo $SECRET" > .env'
      shell: bash
      env:
        SECRET: ${{ secrets.ENV }}

    - name: Deploy docker images
      run: docker compose up -d
