name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Create secret .env file
      run: 'echo "$SECRET" > .env'
      shell: bash
      env:
        SECRET: ${{ secrets.ENV }}
    
    - name: Make sure AI docker image is up to date
      run: docker pull asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/efiss-ai:latest

    - name: Add ssl certs
      run: cp -r /home/thaiminhpv/backend/EFISS-Backend/nginx/certs/ /home/thaiminhpv/devops/backend-runner/_work/EFISS-Backend/EFISS-Backend/nginx/

    - name: Build docker images
      run: docker compose build
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Deploy docker images
      run: docker compose up -d
