name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Make sure everything is correctly installed
      run: |
        if ! command -v docker &> /dev/null
        then
          echo "Cannot find docker, please install docker first"
          exit
        fi
        if ! command -v make &> /dev/null
        then
          echo "Cannot find make, installing make"
          sudo apt update
          sudo apt install make -y
        fi
      shell: bash

    - name: Create SSL certs
      run: 'mkdir -p nginx/certs/ && echo "$FULL_CHAIN" > nginx/certs/fullchain.pem && echo "$PRIVATE_KEY" > nginx/certs/privkey.pem'
      shell: bash
      env:
        FULL_CHAIN: ${{ secrets.FULL_CHAIN }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    - name: Create secret .env file
      run: 'echo "$SECRET" > .env'
      shell: bash
      env:
        SECRET: ${{ vars.ENV }}
    
    - name: Make sure AI docker image is up to date
      run: docker pull asia-southeast1-docker.pkg.dev/even-acumen-386115/efiss/efiss-ai:latest

    - name: Build docker images
      run: docker compose build
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: Deploy docker images
      run: docker compose up -d
